spring:
  application:
    name: guest-service
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    consul:
      host: localhost
      port: 8500
  jackson:    serialization:      fail-on-empty-beans: false
server:
  port: 10002